/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EarthJusticeRole;

import System.Ecosystem;
import System.Enterprise.Enterprise;
import System.UserAccount.UserAccount;
import System.WorkQueue.NonProfitableRequest;
import UserInterface.SocialAwarenessRole.SocialAwarnessJPanel;
import UserInterface.SocialRole.SocialOrgWorkAreaJPanel;
import javax.swing.JPanel;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.media.Media;
import javafx.scene.media.MediaView;
import javax.sound.sampled.*;
import javax.swing.JFrame;
import com.sun.istack.internal.logging.Logger;
import com.teamdev.jxbrowser.chromium.Browser;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;


/**
 *
 * @author nilan
 */
public class WorkRequestJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private NonProfitableRequest request;
    private Ecosystem system;
    private Player player;
    private BufferedInputStream buff;
    private FileInputStream fis;
    private long total_lenghth;
    private long pause;
    private File myFile = null;
    
    
    
    

    /**
     * Creates new form WorkRequestJPanel
     */
    public WorkRequestJPanel(JPanel userProcessContainer, NonProfitableRequest request, UserAccount account, Enterprise enterprise, Ecosystem system) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.account =  account;
        this.enterprise = enterprise;
        this.system = system;
        
    }

    
    
    
     
     private void Audio(){
         try{
         FileInputStream file  = new FileInputStream("C:\\Users\\anish1992\\AED_MYWORK\\SmartCity_Final\\Audio\\AirPollution.wav");
     
         }
         catch(Exception e){
             System.out.println(e);
         }
         
     
     
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStop = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnPlayVideo = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnPlay1 = new javax.swing.JButton();
        btnResume = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        btnStop.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        btnStop.setForeground(new java.awt.Color(204, 0, 0));
        btnStop.setText("STOP AUDIO");
        btnStop.setBorder(new javax.swing.border.MatteBorder(null));
        btnStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnStopMouseReleased(evt);
            }
        });
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnPause.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        btnPause.setForeground(new java.awt.Color(204, 0, 0));
        btnPause.setText("PAUSE AUDIO");
        btnPause.setBorder(new javax.swing.border.MatteBorder(null));
        btnPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPauseMouseReleased(evt);
            }
        });
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        btnPlayVideo.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        btnPlayVideo.setForeground(new java.awt.Color(204, 0, 0));
        btnPlayVideo.setText("PLAY VIDEO");
        btnPlayVideo.setBorder(new javax.swing.border.MatteBorder(null));
        btnPlayVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayVideoActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 0, 0));
        btnBack.setText("<< Back");
        btnBack.setBorder(new javax.swing.border.MatteBorder(null));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnPlay1.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        btnPlay1.setForeground(new java.awt.Color(204, 0, 0));
        btnPlay1.setText("PLAY AUDIO");
        btnPlay1.setBorder(new javax.swing.border.MatteBorder(null));
        btnPlay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPlay1MouseReleased(evt);
            }
        });
        btnPlay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlay1ActionPerformed(evt);
            }
        });

        btnResume.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        btnResume.setForeground(new java.awt.Color(204, 0, 0));
        btnResume.setText("RESUME AUDIO");
        btnResume.setBorder(new javax.swing.border.MatteBorder(null));
        btnResume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnResumeMouseReleased(evt);
            }
        });
        btnResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel1.setText("Response :");

        jTextField1.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N

        jButton1.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 51));
        jButton1.setText("Send");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPlay1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(758, 758, 758)
                                .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnResume, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(758, 758, 758)
                                .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(557, 557, 557)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(101, 101, 101)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnPlayVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(298, 298, 298))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnPlay1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(253, 253, 253)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResume, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128)
                .addComponent(btnPlayVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
     
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
   
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnPlayVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayVideoActionPerformed
        // TODO add your handling code here:
        final Browser browser = new Browser();
      com.teamdev.jxbrowser.chromium.swing.BrowserView browserView = new com.teamdev.jxbrowser.chromium.swing.BrowserView(browser);

      JFrame frame = new JFrame("directionapi.html");
      frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
      frame.add(browserView, BorderLayout.CENTER);
      frame.setSize(900, 500);
      frame.setLocationRelativeTo(null);
      frame.setVisible(true);
      browser.loadURL("https://www.youtube.com/watch?v=e6rglsLy1Ys");
    }//GEN-LAST:event_btnPlayVideoActionPerformed

    private void btnPlay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlay1ActionPerformed

    private void btnResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResumeActionPerformed

    private void btnPlay1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlay1MouseReleased
        JFileChooser chooser = new JFileChooser();
      int val = chooser.showOpenDialog(null);
      if(val == JFileChooser.APPROVE_OPTION){
          
          myFile = chooser.getSelectedFile();
          String song = myFile + "";
          
          String name = chooser.getSelectedFile().getName();
    }
      try{
          fis = new FileInputStream(myFile);
          buff = new BufferedInputStream(fis);
          player = new Player(buff);
          total_lenghth = fis.available();
          
          new Thread(){
              public void run(){
                  try{
                      player.play();
                  }catch(JavaLayerException ex){
                      System.out.println("Exception caught"); 
                  }
              }
          }.start();
    }catch(IOException ex){
        System.out.println("Exception caught");  
      } catch(JavaLayerException ex){
         System.out.println("Exception caught");  
          
      }
    }//GEN-LAST:event_btnPlay1MouseReleased

    private void btnPauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPauseMouseReleased
       if(player != null){
           try{ 
               pause = fis.available();
               
               player.close();
               
           } catch (IOException ex) {
                System.out.println("Exception caught");
            }
            
        }
    }//GEN-LAST:event_btnPauseMouseReleased

    private void btnResumeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResumeMouseReleased
        try{
           fis = new FileInputStream(myFile);
           buff = new BufferedInputStream(fis);
           player = new Player(buff);
           
           fis.skip(total_lenghth-pause);
           new Thread(){
               public void run(){
                   try{
                       player.play();
                  }catch(JavaLayerException ex){
                       System.out.println("Exception caught " + ex);
                  }
                   
                   
               }
           
           }.start();
           
       } catch (FileNotFoundException ex) {
            System.out.println("Exception caught " + ex);
        } catch (JavaLayerException ex) {
            System.out.println("Exception caught " + ex);
        } catch (IOException ex) {
            System.out.println("Exception caught " + ex);
        }
    }//GEN-LAST:event_btnResumeMouseReleased

    private void btnStopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStopMouseReleased
        if(player != null){
            player.close();
        }
    }//GEN-LAST:event_btnStopMouseReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EJWorkAreaJPanel dwjp = (EJWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        request.setAction(jTextField1.getText());
        if(jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter something to send.");
            return;
        }
        request.setStatus("Completed");
        JOptionPane.showMessageDialog(null, "Request message sent");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPlay1;
    private javax.swing.JButton btnPlayVideo;
    private javax.swing.JButton btnResume;
    private javax.swing.JButton btnStop;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
