/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SmartTrafficRole;

import System.Ecosystem;
import System.Enterprise.Enterprise;
import System.Network.Network;
import System.Organization.Organization;
import System.Organization.SmartCityOrganization;
import System.UserAccount.UserAccount;
import System.WorkQueue.DFSRequest;
import UserInterface.VehicalEmissionManagementRole.DFSWorkRequestJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nilan
 */
public class RequestDriverJPanel extends javax.swing.JPanel {
      private JPanel userProcessContainer;
      private DFSRequest request;
      private UserAccount userAccount;
      private Enterprise enterprise;
      private Ecosystem system;
    /**
     * Creates new form RequestDriverJPanel
     */
    

    RequestDriverJPanel(JPanel userProcessContainer, DFSRequest request, UserAccount userAccount, Enterprise enterprise, Ecosystem system) {
       initComponents(); 
       this.userProcessContainer = userProcessContainer;
       this.request = request;
       this.enterprise = enterprise;
       this.userAccount = userAccount;
       this.system = system;
       
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRequestDriver = new javax.swing.JLabel();
        lblRouteInformation = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        routeTextArea = new javax.swing.JTextArea();
        btnRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        lblRequestDriver.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblRequestDriver.setText("Request Driver");

        lblRouteInformation.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblRouteInformation.setText("Route Information");

        routeTextArea.setColumns(20);
        routeTextArea.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        routeTextArea.setRows(5);
        jScrollPane1.setViewportView(routeTextArea);

        btnRequest.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        btnRequest.setForeground(new java.awt.Color(204, 0, 0));
        btnRequest.setText("Request >>");
        btnRequest.setBorder(new javax.swing.border.MatteBorder(null));
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 0, 0));
        btnBack.setText("<< Back");
        btnBack.setBorder(new javax.swing.border.MatteBorder(null));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(lblRouteInformation)
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(929, 929, 929)
                .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRequestDriver)
                .addGap(665, 665, 665))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(471, 471, 471)
                .addComponent(lblRouteInformation)
                .addGap(368, 368, 368)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblRequestDriver)
                .addGap(255, 255, 255)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SmartTrafficWorkAreaJPanel stwajp = (SmartTrafficWorkAreaJPanel) component;
        // stwajp.populateRouteTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        String message = routeTextArea.getText();
        
        DFSRequest request = new DFSRequest();
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Route Request Sent");
        
        Organization org = null;
        for(Network network : system.getNetworkList()){
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) 
        for(Organization organization : enterprise.getOrganizaionDirectory().getOrganizationList()){
            if(organization instanceof SmartCityOrganization){
                org = organization;
                break;
            }
            
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Information shared with drivers!");
        }
      
      }
    
    }//GEN-LAST:event_btnRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRequestDriver;
    private javax.swing.JLabel lblRouteInformation;
    private javax.swing.JTextArea routeTextArea;
    // End of variables declaration//GEN-END:variables
}
